baseURL = "https://moiva.io/blog/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "lanyon"

[permalinks]
  post = ":title"

[params]
  Title = "Moiva.io Blog"
  Tagline = "Moiva tagline"
  Author = "Alexey Antipov"
  DateForm = "Jan 2 2006"
  mainSections = ["post"]
  Github = ""
