baseURL = "https://moiva.io/blog/"
languageCode = "en-us"
title = "My New Hugo Site"
disableXML = true
disableKinds = ["RSS", "section", "taxonomy", "term", "404"]
paginate = 20

[permalinks]
  post = ":title"

[params]
  Title = "Moiva.io Blog"
  Author = "Alexey Antipov"
  DateForm = "Jan 2 2006"
  mainSections = ["post"]
  Github = ""

[markup]
  [markup.highlight]
    codeFences = false

[markup.goldmark.renderer]
  unsafe= true
